// This file provides stub types for development on non-Linux platforms.
// On Linux, bpf2go generates the real types via `go generate`.

//go:build !linux

package tracer

import (
	"fmt"

	"github.com/cilium/ebpf"
)

// observoorObjects contains all BPF objects after loading.
// This is a stub - the real type is generated by bpf2go on Linux.
type observoorObjects struct {
	// Maps
	TrackedPids  *ebpf.Map `ebpf:"tracked_pids"`
	Events       *ebpf.Map `ebpf:"events"`
	SyscallStart *ebpf.Map `ebpf:"syscall_start"`
	OpenatNames  *ebpf.Map `ebpf:"openat_names"`
	ReqStart     *ebpf.Map `ebpf:"req_start"`
	NetRecvStart *ebpf.Map `ebpf:"net_recv_start"`
	FaultStart   *ebpf.Map `ebpf:"fault_start"`

	// Programs
	TraceSysEnterRead      *ebpf.Program `ebpf:"trace_sys_enter_read"`
	TraceSysExitRead       *ebpf.Program `ebpf:"trace_sys_exit_read"`
	TraceSysEnterWrite     *ebpf.Program `ebpf:"trace_sys_enter_write"`
	TraceSysExitWrite      *ebpf.Program `ebpf:"trace_sys_exit_write"`
	TraceSysEnterFutex     *ebpf.Program `ebpf:"trace_sys_enter_futex"`
	TraceSysExitFutex      *ebpf.Program `ebpf:"trace_sys_exit_futex"`
	TraceSysEnterMmap      *ebpf.Program `ebpf:"trace_sys_enter_mmap"`
	TraceSysExitMmap       *ebpf.Program `ebpf:"trace_sys_exit_mmap"`
	TraceSysEnterEpollWait *ebpf.Program `ebpf:"trace_sys_enter_epoll_wait"`
	TraceSysExitEpollWait  *ebpf.Program `ebpf:"trace_sys_exit_epoll_wait"`
	TraceSysEnterOpenat    *ebpf.Program `ebpf:"trace_sys_enter_openat"`
	TraceSysExitOpenat     *ebpf.Program `ebpf:"trace_sys_exit_openat"`
	TraceSysEnterClose     *ebpf.Program `ebpf:"trace_sys_enter_close"`
	TraceBlockRqIssue      *ebpf.Program `ebpf:"trace_block_rq_issue"`
	TraceBlockRqComplete   *ebpf.Program `ebpf:"trace_block_rq_complete"`
	KprobeTcpSendmsg       *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeTcpRecvmsg       *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KretprobeTcpRecvmsg    *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg"`
	TraceSchedSwitch       *ebpf.Program `ebpf:"trace_sched_switch"`
	KprobeHandleMmFault    *ebpf.Program `ebpf:"kprobe_handle_mm_fault"`
	KretprobeHandleMmFault *ebpf.Program `ebpf:"kretprobe_handle_mm_fault"`
}

func (o *observoorObjects) Close() error {
	return nil
}

// loadObservoor returns an error on non-Linux platforms.
func loadObservoor() (*ebpf.CollectionSpec, error) {
	return nil, fmt.Errorf("BPF programs can only be loaded on Linux")
}
